### TESTE 1: Cadastrar um novo produto
POST https://localhost:7018/api/produtos
Content-Type: application/json
{
  "codigo": 101,
  "descricao": "Parafuso Sextavado",
  "saldo": 50
}
### TESTE 2: Buscar o produto que acabamos de criar
GET https://localhost:7018/api/produtos/101

###

### TESTE 3: Buscar um produto que não existe
GET https://localhost:7018/api/produtos/999