### TESTE 1: Cadastrar um produto (Estoque)
POST https://localhost:7018/api/produtos
Content-Type: application/json

{
  "codigo": 101,
  "descricao": "Produto A",
  "saldo": 10
}

### TESTE 2: Cadastrar uma Nota Fiscal (Faturamento)
POST https://localhost:7049/api/notasfiscais
Content-Type: application/json

[
  {
    "codigoProduto": 101,
    "quantidade": 3,
    "descricaoProduto": "Produto A"
  }
]

### TESTE 3: IMPRIMIR A NOTA (MAIN)
POST https://localhost:7049/api/notasfiscais/1/imprimir

### TESTE 4: Verificar o Status da Nota (Faturamento)
GET https://localhost:7049/api/notasfiscais/1

### TESTE 5: Verificar o Saldo do Produto (Estoque)
GET https://localhost:7018/api/produtos/101

### TESTE 6: Tentar imprimir a nota JÁ FECHADA
POST https://localhost:7049/api/notasfiscais/1/imprimir

### TESTE 7: Tentar imprimir uma nota com ESTOQUE INSUFICIENTE
POST https://localhost:7049/api/notasfiscais
Content-Type: application/json

[
  {
    "codigoProduto": 101,
    "quantidade": 50,
    "descricaoProduto": "Produto A"
  }
]

### TESTE 8: Tentar imprimir a Nota 2
POST https://localhost:7049/api/notasfiscais/2/imprimir