### TESTE 1: Cadastrar a primeira Nota Fiscal (POST)
# (Isso deve criar a Nota Fiscal de número 1)
POST https://localhost:7049/api/notasfiscais
Content-Type: application/json

[
  {
    "codigoProduto": 101,
    "quantidade": 2,
    "descricaoProduto": "Parafuso Sextavado"
  },
  {
    "codigoProduto": 102,
    "quantidade": 5,
    "descricaoProduto": "Porca"
  }
]

###
### TESTE 2: Buscar a Nota Fiscal número 1 (GET)
# (Isso deve retornar a nota que acabamos de criar)
GET https://localhost:7049/api/notasfiscais/1

###
### TESTE 3: Cadastrar a segunda Nota Fiscal (POST)
# (Isso deve criar a Nota Fiscal de número 2 - testando a sequência)
POST https://localhost:7049/api/notasfiscais
Content-Type: application/json

[
  {
    "codigoProduto": 205,
    "quantidade": 10,
    "descricaoProduto": "Arruela"
  }
]

###
### TESTE 4: Buscar a Nota Fiscal número 2 (GET)
GET https://localhost:7049/api/notasfiscais/2

###
### TESTE 5: Buscar uma nota que não existe (GET)
# (Isso deve retornar 404 Not Found)
GET https://localhost:7049/api/notasfiscais/999